backend:
  name: git-gateway
  branch: main # GitHubのブランチ名がmasterならここをmasterに書き換え

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "posts"
    label: "ブログ記事"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "作成日", name: "date", widget: "datetime"}
      - {label: "本文", name: "body", widget: "markdown"}
